name: Ping Website

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 2 minute

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize ping count
      run: |
        if [ ! -f .ping_count ]; then
          echo 0 > .ping_count
        fi

    - name: Read ping count
      id: read_count
      run: |
        count=$(cat .ping_count)
        echo "Ping count: $count"
        echo "::set-output name=count::$count"

    - name: Stop if limit reached
      if: ${{ steps.read_count.outputs.count == '2' }}  # Stop after 2 ping test
      run: |
        echo "Ping limit reached. Stopping."
        exit 0 # Stop the workflow

    - name: Ping website
      if: ${{ steps.read_count.outputs.count != '2' }}
      run: |
        curl -I https://hbn-database.streamlit.app/
        count=${{ steps.read_count.outputs.count }}
        new_count=$((count + 1))
        echo $new_count > .ping_count
        git config --global user.email "theory@qcs.cit.tum.de"
        git config --global user.name "QCS-Theory"
        git add .ping_count
        git commit -m "Ping count update: $new_count"
        git push origin main